#!/bin/python3

import math
import os
import random
import re
import sys

def balik():
    for i in reversed(arr):
        print(i, end=' ')

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))
    balik()
